[package]
name = "liboqs-rs-bindings"
version = "0.1.0"
authors = ["Alexander Nilsson <a.code@nilsson.link>"]
edition = "2018"

[dependencies]
log = "0.4"
num = "*"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
bindgen = "0.54.0"